### ISSUE TITLE
wireless connection issue in Ubuntu

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise#70]
When running the [das5](https://github.com/MD-Studio/cerise-mdstudio-das5) specialization  from an Ubuntu host machine, the application hangs indefinitely without reporting any error or performing any action.

the cerise log reports:
```
[2018-01-10 09:50:46.074] [INFO] Starting up [root]
[2018-01-10 09:50:46.079] [DEBUG] scheme: sftp, location: fs0.das5.cs.vu.nl, credential: PasswordCredentialImplementation [adaptorName=ssh, username=fzapata] [cerise.config]
```

The docker logs
```
~ $ docker logs b820530aad5d
 * Starting nginx nginx
   ...done.
```

**Comment by LourensVeen** [comment]
This seems to be a network issue, that DEBUG log message is written right before it connects for the first time. Probably something to do with DNS or firewall, or a combination of such. It works fine for me, but I've had Docker/DNS issues with the network that we're using here before and changed my setup to work better, so that may explain the difference.

**Comment by LourensVeen** [comment]
Network issue confirmed. For what it's worth, Ubuntu configures Docker's internal DNS server to connect directly to Google's public DNS. The network that we are on does not allow DNS queries to any DNS servers other than the local one, so the DNS queries fail, and programs running inside Docker containers cannot connect.

There's a complicated way to fix this using an additional dnsmasq and some configuration wizardry to have Docker use that second dnsmasq, which then forwards to the standard Ubuntu dnsmasq, which forwards to the local DNS server because it got it from DHCP. As it was, Felipe could switch to a different network which does allow external DNS. That's all way beyond the scope of Cerise though.
