### ISSUE TITLE
error checking cerise job class

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise#77]
I have made a mistake an introduced a typo in a `cwl` file such that the class was:
```
class: CommandLineToolv
```
This generates the following uninformative error:
```
  File "/home/fzapata/.cerise/api/files/cerise/cwltiny.py", line 639, in <module>
    has_error, output_dict = run_workflow(workdir_path, cwl_dict, input_dict)
  File "/home/fzapata/.cerise/api/files/cerise/cwltiny.py", line 610, in run_workflow
    step_error = execute_workflow_step(step)
  File "/home/fzapata/.cerise/api/files/cerise/cwltiny.py", line 559, in execute_workflow_step
    log("Step output: {}\n".format(json.dumps(output_dict, indent=4)))
UnboundLocalError: local variable 'output_dict' referenced before assignment
```

**Comment by LourensVeen** [comment]
There are two issues here: the incorrect class isn't detected properly, and a step with a missing output doesn't generate a proper error message.

The first issue was fixed in https://github.com/MD-Studio/cwltiny/commit/498fc69a065a47eb09c166b453197a960af5cb34, the second one in https://github.com/MD-Studio/cwltiny/commit/8df1a5bb56df2296aaf871a34284f246dad09dd5. As of https://github.com/MD-Studio/cerise/commit/5206296ff7f820577a1006d76619b72a26057eeb, these are now both included in Cerise.
